### ISSUE TITLE
No public function exists to retrieve installation id

### ISSUE THREAD

**Issue by ghost** [spotify/github-java-client#124]
The documentation mentions: "_Then, you can scope the client for a specific Installation ID, to do the operations at the installation level_"

However, there does not seem to be any public function that can retrieve the Installation ID

**Comment by felix-seifert** [comment]
Indeed, we do not have a specific function for retrieving just the installation ID. However, we have several methods which retrieve the whole [`Installation`](https://github.com/spotify/github-java-client/blob/master/src/main/java/com/spotify/github/v3/checks/Installation.java). You can, for example, use the method [`getInstalltion()` in our `GithubAppClient`](https://github.com/spotify/github-java-client/blob/d4a0d3cf9423878ab70936a8b192afe39c6c954e/src/main/java/com/spotify/github/v3/clients/GithubAppClient.java#L85) to retrieve the `Installation`. You can then retrieve the ID from the returned object. Maybe the following example gives some clarity:

```
githubClient.createOrganisationClient(org).createGithubAppClient().getInstallation().join().id();
```

Please reach out if you have further questions. If you want, you can create some documentation about retrieving the actual installation ID.
