### ISSUE TITLE
Latest Release is 0.0.18 but latest tag is 0.0.25

### ISSUE THREAD

**Issue by tedyoung** [spotify/github-java-client#64]
The latest release (shown in the sidebar on the GitHub repo page) is 0.0.18, which is not the latest available artifact.

(This confused me when I was looking for the `Repository.isCollaborator` method, which was after 0.0.18).

**Comment by tedyoung** [comment]
Is there a way to get Tags marked as Releases as well? It's playing havoc with my dependency tool.

**Comment by Abhi347** [comment]
The tags are not automatically creating the releases. It's a manual process as far as I know. But let me still take a look and see if we can automate it.

**Comment by felix-seifert** [comment]
We [create a GitHub release](https://github.com/spotify/github-java-client/blob/master/.github/workflows/release-on-github.yml) automatically [whenever we release on Maven Central](https://github.com/spotify/github-java-client/blob/d4a0d3cf9423878ab70936a8b192afe39c6c954e/.github/workflows/release.yml#L71). As the release on Maven Central happens for every tagged commit, we should usually be in sync.

The current [version on Maven central is 0.2.12](https://repo1.maven.org/maven2/com/spotify/github-client/0.2.12/). And the current [GitHub release is 0.2.12](https://github.com/spotify/github-java-client/releases/tag/v0.2.12) as well.
